export default class Customer {
  Id;
  Code;
  AccountId;
  Lastname;
  Firstname;
  Gender;
  Birthday;
  City;
  Country;
  Address;
  Phone;
  CIC;
  CreatedAt = null;
  UpdatedAt = null;

  constructor({
    id,
    code,
    accountId,
    lastname,
    firstname,
    gender,
    birthday,
    city,
    country,
    address,
    phone,
    cic,
    createdAt,
    updatedAt,
  } = {}) {
    this.Id = id;
    this.Code = code;
    this.AccountId = accountId;
    this.Lastname = lastname;
    this.Firstname = firstname;
    this.Gender = gender;
    this.Birthday = birthday;
    this.City = city;
    this.Country = country;
    this.Address = address;
    this.Phone = phone;
    this.CIC = cic;
    this.CreatedAt = createdAt;
    this.UpdatedAt = updatedAt;
  }
  static fromDb(row) {
    if (!row) return null;
    return new Customer({
      id: row.CustomerId,
      code: row.CustomerCode,
      accountId: row.AccountId,
      lastname: row.Lastname,
      firstname: row.Firstname,
      gender: row.Gender,
      Birthday: row.Birthday,
      City: row.City,
      country: row.Country,
      address: row.Address,
      phone: row.Phone,
      cic: row.CIC,
      createdAt: row.CreatedAt,
      updatedAt: row.UpdatedAt,
    });
  }

  toInsertParams() {
    // first element must be CustomerCode, matching the column order in
    // customerRepo.create.  The Id is not included because it is generated by
    // the database.
    return [
      this.Code,
      this.AccountId,
      this.Lastname,
      this.Firstname,
      this.Gender,
      this.Birthday,
      this.City,
      this.Country,
      this.Address,
      this.Phone,
      this.CIC,
      this.CreatedAt,
      this.UpdatedAt,
    ];
  }

  toUpdateParams() {
    // Code is not updatable here; we leave it out of the parameter list.
    return [
      this.AccountId,
      this.Lastname,
      this.Firstname,
      this.Gender,
      this.Birthday,
      this.City,
      this.Country,
      this.Address,
      this.Phone,
      this.CIC,
      this.CreatedAt,
      this.UpdatedAt,
      this.Id,
    ];
  }

  validate() {
    const errors = [];
    if (!this.AccountId) {
      errors.push({ field: "AccountId", message: "AccountId is required" });
    }
    if (!this.Lastname || !this.Lastname.trim()) {
      errors.push({ field: "Lastname", message: "Lastname is required" });
    }
    if (!this.Firstname || !this.Firstname.trim()) {
      errors.push({ field: "Firstname", message: "Firstname is required" });
    }
    // more checks can be added as needed
    return errors;
  }
}
